### PR TITLE
Beautified the converter chips

### PR DESCRIPTION
**Pull request by DoozyDoz**
Screenshot 2022-09-12 165753
Screenshot 2022-09-12 171229

### CODE REVIEW

**Comment by prathameshmm02** [comment]
Thanks for your contribution. In my opinion, svg's would be better for icons, let me know if it's possible. So, I'll merge.

**Comment by DoozyDoz** [comment]
Done

**Comment by DoozyDoz** [comment]
@prathameshmm02 Please reopen the PR
- The chips were not updated for the horizontal view

**Comment by prathameshmm02** [comment]
Oh, it's okay, create a new PR @DoozyDoz.

**Pull request merged**
