### PR TITLE
initial fastlane structure

### PR DESCRIPTION
**Pull request by IzzySoft**
Fastlane Starter Package (see [here](https://gitlab.com/IzzyOnDroid/repo/-/issues/261) for details). Helpful links to build on this:

* my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688)
* hints on formatting `full_description.txt` [in my wiki](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane)

Enjoy :smiley:

### CODE REVIEW

**Comment by IzzySoft** [comment]
Yay! Config updated here in my repo so changes will be pulled whenever you released a new version. Should you add a featureGraphic or per-release changelogs, please drop me a note so I can see to enable them here as well. Thanks!

**Comment by prathameshmm02** [comment]
Hey @IzzySoft, I've added a featureGraphic and changelog for the next version.

**Comment by IzzySoft** [comment]
Apologies for the late reply, but Github notifications had stopped reaching my mailbox :cry: (hopefully fixed now). I've just grabbed the files and placed them manually, as the new release was already fetched by my updater. Updated the config as well to consider them next time. Thanks a lot!

**Comment by Poussinou** [comment]
Hi,

Is there any reason we don't try to add this app in F-Droid directly? :)

**Comment by IzzySoft** [comment]
If you want an easy way, you can check [this chapter](https://android.izzysoft.de/articles/named/fdroid-intro-2#rfp) of my F-Droid blog series.

**Comment by prathameshmm02** [comment]
Thanks, I'll take a look.

**Comment by IzzySoft** [comment]
And if you need help, we are here (disclosure: I'm one of the F-Droid maintainers).

**Comment by prathameshmm02** [comment]
Can you guys have a look at the [rfp issue](https://gitlab.com/fdroid/rfp/-/issues/2100)?

**Pull request merged**
